git clone https://github.com/elasticjob/elastic-job-lite.git
git clone https://github.com/unbxd/java-sdk.git
git clone https://github.com/sofastack/sofa-jarslink.git
git clone https://github.com/vdurmont/emoji-java.git
git clone https://github.com/knightliao/disconf.git
git clone https://github.com/google/openrtb.git
git clone https://github.com/optimaize/language-detector.git
git clone https://github.com/alibaba/jvm-sandbox.git
git clone https://github.com/searchbox-io/Jest.git
git clone https://github.com/fasseg/exp4j.git
git clone https://github.com/PhantomYdn/jlll.git
git clone https://github.com/codeforamerica/open311_java.git
git clone https://github.com/qos-ch/logback.git
git clone https://github.com/rapidoid/rapidoid.git
git clone https://github.com/sarxos/webcam-capture.git
git clone https://github.com/lets-blade/blade.git
git clone https://github.com/deeplearning4j/nd4j.git
git clone https://github.com/apache/activemq.git
git clone https://github.com/dvare/dvare-framework.git
git clone https://github.com/pasha4j/xacml4j.git
git clone https://github.com/samskivert/jmustache.git
git clone https://github.com/jmxtrans/jmxtrans.git
