git clone https://github.com/microsoft/lsif-java.git
git clone https://github.com/eclipse/eclipse.jdt.ls.git
git clone https://github.com/koushikr/jelastic.git
git clone https://github.com/quarkusio/quarkus.git
git clone https://github.com/orientechnologies/orientdb.git
git clone https://github.com/sofastack/sofa-jraft.git
git clone https://github.com/NanoHttpd/nanohttpd.git
git clone https://github.com/ivan-vasilev/neuralnetworks.git
git clone https://github.com/Kong/unirest-java.git
git clone https://github.com/pmd/pmd.git
git clone https://github.com/BroadleafCommerce/BroadleafCommerce.git
git clone https://github.com/mabe02/lanterna.git
git clone https://github.com/joschi/JadConfig.git
git clone https://github.com/apache/kylin.git
git clone https://github.com/spring-cloud/spring-cloud-gateway.git
git clone https://github.com/alibaba/druid.git
git clone https://github.com/hazelcast/hazelcast.git
git clone https://github.com/dbi1463/SortDescriptor.git
git clone https://github.com/zxing/zxing.git
git clone https://github.com/btc-ag/service-idl.git
git clone https://github.com/eclipse/jetty.project.git
git clone https://github.com/ptitjes/jlato.git
git clone https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition.git
git clone https://github.com/oasis-open/openc2-lycan-java.git
git clone https://github.com/daniloarcidiacono/commons-lang.git
git clone https://github.com/spring-cloud/spring-cloud-netflix.git
git clone https://github.com/panda-lang/panda.git
git clone https://github.com/apache/hbase.git
git clone https://github.com/ctripcorp/apollo.git
git clone https://github.com/raphw/byte-buddy.git
git clone https://github.com/alibaba/jetcache.git
git clone https://github.com/alibaba/arthas.git
git clone https://github.com/spotify/apollo.git
git clone https://github.com/jeremylong/DependencyCheck.git
git clone https://github.com/brunocvcunha/mdmlang.git
git clone https://github.com/lettuce-io/lettuce-core.git
git clone https://github.com/Anil-Adhikari/IMPL.git
git clone https://github.com/pure4j/pure4j.git
git clone https://github.com/amaembo/streamex.git
git clone https://github.com/brettwooldridge/HikariCP.git
git clone https://github.com/gerryai/pddl-parser.git
git clone https://github.com/sofastack/sofa-rpc.git
git clone https://github.com/automate-website/waml-io.git
git clone https://github.com/atomix/atomix.git
git clone https://github.com/xuhuisheng/lemon.git
git clone https://github.com/apache/pulsar.git
git clone https://github.com/apache/skywalking.git
git clone https://github.com/jtablesaw/tablesaw.git
git clone https://github.com/docker-java/docker-java.git
git clone https://github.com/FINRAOS/JTAF-XCore.git
git clone https://github.com/MorphiaOrg/morphia.git
git clone https://github.com/OryxProject/oryx.git
git clone https://github.com/apache/dubbo.git
git clone https://github.com/jersey/jersey.git
git clone https://github.com/square/keywhiz.git
git clone https://github.com/modelmapper/modelmapper.git
git clone https://github.com/alibaba/fastjson.git
git clone https://github.com/opentracing/opentracing-java.git
git clone https://github.com/AxonFramework/AxonFramework.git
git clone https://github.com/mybatis/mybatis-3.git
git clone https://github.com/netty/netty.git
git clone https://github.com/JanusGraph/janusgraph.git
git clone https://github.com/speedment/speedment.git
