git clone https://github.com/jdeferred/jdeferred.git
git clone https://github.com/fossasia/susi_server.git
git clone https://github.com/Squarespace/template-compiler.git
git clone https://github.com/skylot/jadx.git
git clone https://github.com/CalebFenton/simplify.git
git clone https://github.com/pedrovgs/AndroidWiFiADB.git
git clone https://github.com/reactor/reactor-core.git
git clone https://github.com/gocd/gocd.git
git clone https://github.com/xbib/cql.git
git clone https://github.com/chennaione/sugar.git
git clone https://github.com/oblac/jodd.git
git clone https://github.com/vavr-io/vavr.git
git clone https://github.com/aNNiMON/Lightweight-Stream-API.git
git clone https://github.com/mambu-gmbh/number2words.git
git clone https://github.com/azkaban/azkaban.git
git clone https://github.com/madisp/stupid.git
git clone https://github.com/appium/java-client.git
git clone https://github.com/spring-projects/spring-integration-samples.git
git clone https://github.com/ehcache/ehcache3.git
git clone https://github.com/spotinst/spotinst-sdk-java.git
git clone https://github.com/googlemaps/google-maps-services-java.git
git clone https://github.com/crate/crate.git
