call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/elasticjob#elastic-job-lite
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/unbxd#java-sdk
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/sofastack#sofa-jarslink
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/vdurmont#emoji-java
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/knightliao#disconf
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/google#openrtb
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/optimaize#language-detector
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/alibaba#jvm-sandbox
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/searchbox-io#Jest
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/fasseg#exp4j
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/PhantomYdn#jlll
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/codeforamerica#open311_java
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/qos-ch#logback
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/rapidoid#rapidoid
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/sarxos#webcam-capture
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/lets-blade#blade
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/deeplearning4j#nd4j
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/apache#activemq
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/dvare#dvare-framework
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/pasha4j#xacml4j
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/samskivert#jmustache
call mvn clean cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.test.failure.ignore=true -f ALLPROJECTS/MAVEN/COBERTURA/jmxtrans#jmxtrans
