git clone https://github.com/alibaba/jvm-sandbox.git ALLPROJECTS/MAVEN/COBERTURA/alibaba#jvm-sandbox
git clone https://github.com/apache/zeppelin.git ALLPROJECTS/MAVEN/COBERTURA/apache#zeppelin
git clone https://github.com/citerus/dddsample-core.git ALLPROJECTS/MAVEN/COBERTURA/citerus#dddsample-core
git clone https://github.com/codeforamerica/open311_java.git ALLPROJECTS/MAVEN/COBERTURA/codeforamerica#open311_java
git clone https://github.com/CrawlScript/WebCollector.git ALLPROJECTS/MAVEN/COBERTURA/CrawlScript#WebCollector
git clone https://github.com/dvare/dvare-framework.git ALLPROJECTS/MAVEN/COBERTURA/dvare#dvare-framework
git clone https://github.com/elasticjob/elastic-job-lite.git ALLPROJECTS/MAVEN/COBERTURA/elasticjob#elastic-job-lite
git clone https://github.com/fasseg/exp4j.git ALLPROJECTS/MAVEN/COBERTURA/fasseg#exp4j
git clone https://github.com/google/openrtb.git ALLPROJECTS/MAVEN/COBERTURA/google#openrtb
git clone https://github.com/knightliao/disconf.git ALLPROJECTS/MAVEN/COBERTURA/knightliao#disconf
git clone https://github.com/lets-blade/blade.git ALLPROJECTS/MAVEN/COBERTURA/lets-blade#blade
git clone https://github.com/nutzam/nutz.git ALLPROJECTS/MAVEN/COBERTURA/nutzam#nutz
git clone https://github.com/optimaize/language-detector.git ALLPROJECTS/MAVEN/COBERTURA/optimaize#language-detector
git clone https://github.com/pasha4j/xacml4j.git ALLPROJECTS/MAVEN/COBERTURA/pasha4j#xacml4j
git clone https://github.com/PhantomYdn/jlll.git ALLPROJECTS/MAVEN/COBERTURA/PhantomYdn#jlll
git clone https://github.com/samskivert/jmustache.git ALLPROJECTS/MAVEN/COBERTURA/samskivert#jmustache
git clone https://github.com/sofastack/sofa-jarslink.git ALLPROJECTS/MAVEN/COBERTURA/sofastack#sofa-jarslink
git clone https://github.com/twitter/distributedlog.git ALLPROJECTS/MAVEN/COBERTURA/twitter#distributedlog
git clone https://github.com/unbxd/java-sdk.git ALLPROJECTS/MAVEN/COBERTURA/unbxd#java-sdk
