git clone https://github.com/alibaba/arthas.git ALLPROJECTS/MAVEN/JACOCO/alibaba#arthas
git clone https://github.com/alibaba/canal.git ALLPROJECTS/MAVEN/JACOCO/alibaba#canal
git clone https://github.com/alibaba/druid.git ALLPROJECTS/MAVEN/JACOCO/alibaba#druid
git clone https://github.com/alibaba/fastjson.git ALLPROJECTS/MAVEN/JACOCO/alibaba#fastjson
git clone https://github.com/alibaba/nacos.git ALLPROJECTS/MAVEN/JACOCO/alibaba#nacos
git clone https://github.com/alibaba/Sentinel.git ALLPROJECTS/MAVEN/JACOCO/alibaba#Sentinel
git clone https://github.com/alibaba/spring-cloud-alibaba.git ALLPROJECTS/MAVEN/JACOCO/alibaba#spring-cloud-alibaba
git clone https://github.com/alibaba/transmittable-thread-local.git ALLPROJECTS/MAVEN/JACOCO/alibaba#transmittable-thread-local
git clone https://github.com/Anil-Adhikari/IMPL.git ALLPROJECTS/MAVEN/JACOCO/Anil-Adhikari#IMPL
git clone https://github.com/apache/dubbo.git ALLPROJECTS/MAVEN/JACOCO/apache#dubbo
git clone https://github.com/apache/hbase.git ALLPROJECTS/MAVEN/JACOCO/apache#hbase
git clone https://github.com/apache/incubator-pinot.git ALLPROJECTS/MAVEN/JACOCO/apache#incubator-pinot
git clone https://github.com/apache/incubator-shardingsphere.git ALLPROJECTS/MAVEN/JACOCO/apache#incubator-shardingsphere
git clone https://github.com/apache/kylin.git ALLPROJECTS/MAVEN/JACOCO/apache#kylin
git clone https://github.com/apache/rocketmq.git ALLPROJECTS/MAVEN/JACOCO/apache#rocketmq
git clone https://github.com/apache/shiro.git ALLPROJECTS/MAVEN/JACOCO/apache#shiro
git clone https://github.com/automate-website/waml-io.git ALLPROJECTS/MAVEN/JACOCO/automate-website#waml-io
git clone https://github.com/b3log/solo.git ALLPROJECTS/MAVEN/JACOCO/b3log#solo
git clone https://github.com/brettwooldridge/HikariCP.git ALLPROJECTS/MAVEN/JACOCO/brettwooldridge#HikariCP
git clone https://github.com/brunocvcunha/mdmlang.git ALLPROJECTS/MAVEN/JACOCO/brunocvcunha#mdmlang
git clone https://github.com/btc-ag/service-idl.git ALLPROJECTS/MAVEN/JACOCO/btc-ag#service-idl
git clone https://github.com/checkstyle/checkstyle.git ALLPROJECTS/MAVEN/JACOCO/checkstyle#checkstyle
git clone https://github.com/chewiebug/GCViewer.git ALLPROJECTS/MAVEN/JACOCO/chewiebug#GCViewer
git clone https://github.com/codecentric/spring-boot-admin.git ALLPROJECTS/MAVEN/JACOCO/codecentric#spring-boot-admin
git clone https://github.com/ctripcorp/apollo.git ALLPROJECTS/MAVEN/JACOCO/ctripcorp#apollo
git clone https://github.com/daniloarcidiacono/commons-lang.git ALLPROJECTS/MAVEN/JACOCO/daniloarcidiacono#commons-lang
git clone https://github.com/dbi1463/SortDescriptor.git ALLPROJECTS/MAVEN/JACOCO/dbi1463#SortDescriptor
git clone https://github.com/dropwizard/dropwizard.git ALLPROJECTS/MAVEN/JACOCO/dropwizard#dropwizard
git clone https://github.com/eclipse/eclipse.jdt.ls.git ALLPROJECTS/MAVEN/JACOCO/eclipse#eclipse.jdt.ls
git clone https://github.com/eclipse/jetty.project.git ALLPROJECTS/MAVEN/JACOCO/eclipse#jetty.project
git clone https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition.git ALLPROJECTS/MAVEN/JACOCO/EnterpriseQualityCoding#FizzBuzzEnterpriseEdition
git clone https://github.com/Ethico/java-8-samples.git ALLPROJECTS/MAVEN/JACOCO/Ethico#java-8-samples
git clone https://github.com/FINRAOS/JTAF-XCore.git ALLPROJECTS/MAVEN/JACOCO/FINRAOS#JTAF-XCore
git clone https://github.com/flowable/flowable-engine.git ALLPROJECTS/MAVEN/JACOCO/flowable#flowable-engine
git clone https://github.com/gerryai/pddl-parser.git ALLPROJECTS/MAVEN/JACOCO/gerryai#pddl-parser
git clone https://github.com/hazelcast/hazelcast.git ALLPROJECTS/MAVEN/JACOCO/hazelcast#hazelcast
git clone https://github.com/iluwatar/java-design-patterns.git ALLPROJECTS/MAVEN/JACOCO/iluwatar#java-design-patterns
git clone https://github.com/JanusGraph/janusgraph.git ALLPROJECTS/MAVEN/JACOCO/JanusGraph#janusgraph
git clone https://github.com/javaparser/javaparser.git ALLPROJECTS/MAVEN/JACOCO/javaparser#javaparser
git clone https://github.com/JCTools/JCTools.git ALLPROJECTS/MAVEN/JACOCO/JCTools#JCTools
git clone https://github.com/jenkinsci/blueocean-plugin.git ALLPROJECTS/MAVEN/JACOCO/jenkinsci#blueocean-plugin
git clone https://github.com/jersey/jersey.git ALLPROJECTS/MAVEN/JACOCO/jersey#jersey
git clone https://github.com/joschi/JadConfig.git ALLPROJECTS/MAVEN/JACOCO/joschi#JadConfig
git clone https://github.com/koushikr/jelastic.git ALLPROJECTS/MAVEN/JACOCO/koushikr#jelastic
git clone https://github.com/lettuce-io/lettuce-core.git ALLPROJECTS/MAVEN/JACOCO/lettuce-io#lettuce-core
git clone https://github.com/mcxiaoke/android-volley.git ALLPROJECTS/MAVEN/JACOCO/mcxiaoke#android-volley
git clone https://github.com/Meituan-Dianping/Leaf.git ALLPROJECTS/MAVEN/JACOCO/Meituan-Dianping#Leaf
git clone https://github.com/microsoft/lsif-java.git ALLPROJECTS/MAVEN/JACOCO/microsoft#lsif-java
git clone https://github.com/mybatis/mybatis-3.git ALLPROJECTS/MAVEN/JACOCO/mybatis#mybatis-3
git clone https://github.com/NanoHttpd/nanohttpd.git ALLPROJECTS/MAVEN/JACOCO/NanoHttpd#nanohttpd
git clone https://github.com/netty/netty.git ALLPROJECTS/MAVEN/JACOCO/netty#netty
git clone https://github.com/networknt/light-4j.git ALLPROJECTS/MAVEN/JACOCO/networknt#light-4j
git clone https://github.com/oasis-open/openc2-lycan-java.git ALLPROJECTS/MAVEN/JACOCO/oasis-open#openc2-lycan-java
git clone https://github.com/OpenRefine/OpenRefine.git ALLPROJECTS/MAVEN/JACOCO/OpenRefine#OpenRefine
git clone https://github.com/oracle/opengrok.git ALLPROJECTS/MAVEN/JACOCO/oracle#opengrok
git clone https://github.com/panda-lang/panda.git ALLPROJECTS/MAVEN/JACOCO/panda-lang#panda
git clone https://github.com/ptitjes/jlato.git ALLPROJECTS/MAVEN/JACOCO/ptitjes#jlato
git clone https://github.com/pure4j/pure4j.git ALLPROJECTS/MAVEN/JACOCO/pure4j#pure4j
git clone https://github.com/quarkusio/quarkus.git ALLPROJECTS/MAVEN/JACOCO/quarkusio#quarkus
git clone https://github.com/querydsl/querydsl.git ALLPROJECTS/MAVEN/JACOCO/querydsl#querydsl
git clone https://github.com/raphw/byte-buddy.git ALLPROJECTS/MAVEN/JACOCO/raphw#byte-buddy
git clone https://github.com/roboguice/roboguice.git ALLPROJECTS/MAVEN/JACOCO/roboguice#roboguice
git clone https://github.com/seata/seata.git ALLPROJECTS/MAVEN/JACOCO/seata#seata
git clone https://github.com/sofastack/sofa-rpc.git ALLPROJECTS/MAVEN/JACOCO/sofastack#sofa-rpc
git clone https://github.com/spotify/helios.git ALLPROJECTS/MAVEN/JACOCO/spotify#helios
git clone https://github.com/spring-cloud/spring-cloud-netflix.git ALLPROJECTS/MAVEN/JACOCO/spring-cloud#spring-cloud-netflix
git clone https://github.com/spring-projects/spring-petclinic.git ALLPROJECTS/MAVEN/JACOCO/spring-projects#spring-petclinic
git clone https://github.com/square/keywhiz.git ALLPROJECTS/MAVEN/JACOCO/square#keywhiz
git clone https://github.com/swagger-api/swagger-core.git ALLPROJECTS/MAVEN/JACOCO/swagger-api#swagger-core
git clone https://github.com/szerhusenBC/jwt-spring-security-demo.git ALLPROJECTS/MAVEN/JACOCO/szerhusenBC#jwt-spring-security-demo
git clone https://github.com/thinkaurelius/titan.git ALLPROJECTS/MAVEN/JACOCO/thinkaurelius#titan
git clone https://github.com/undertow-io/undertow.git ALLPROJECTS/MAVEN/JACOCO/undertow-io#undertow
git clone https://github.com/wildfly/wildfly.git ALLPROJECTS/MAVEN/JACOCO/wildfly#wildfly
git clone https://github.com/zxing/zxing.git ALLPROJECTS/MAVEN/JACOCO/zxing#zxing
