git clone https://github.com/jdeferred/jdeferred.git ALLPROJECTS/GRADLE/JACOCO/jdeferred#jdeferred
git clone https://github.com/fossasia/susi_server.git ALLPROJECTS/GRADLE/JACOCO/fossasia#susi_server
git clone https://github.com/Squarespace/template-compiler.git ALLPROJECTS/GRADLE/JACOCO/Squarespace#template-compiler
git clone https://github.com/skylot/jadx.git ALLPROJECTS/GRADLE/JACOCO/skylot#jadx
git clone https://github.com/CalebFenton/simplify.git ALLPROJECTS/GRADLE/JACOCO/CalebFenton#simplify
git clone https://github.com/pedrovgs/AndroidWiFiADB.git ALLPROJECTS/GRADLE/JACOCO/pedrovgs#AndroidWiFiADB
git clone https://github.com/reactor/reactor-core.git ALLPROJECTS/GRADLE/JACOCO/reactor#reactor-core
git clone https://github.com/gocd/gocd.git ALLPROJECTS/GRADLE/JACOCO/gocd#gocd
git clone https://github.com/xbib/cql.git ALLPROJECTS/GRADLE/JACOCO/xbib#cql
git clone https://github.com/chennaione/sugar.git ALLPROJECTS/GRADLE/JACOCO/chennaione#sugar
git clone https://github.com/oblac/jodd.git ALLPROJECTS/GRADLE/JACOCO/oblac#jodd
git clone https://github.com/vavr-io/vavr.git ALLPROJECTS/GRADLE/JACOCO/vavr-io#vavr
git clone https://github.com/aNNiMON/Lightweight-Stream-API.git ALLPROJECTS/GRADLE/JACOCO/aNNiMON#Lightweight-Stream-API
git clone https://github.com/mambu-gmbh/number2words.git ALLPROJECTS/GRADLE/JACOCO/mambu-gmbh#number2words
git clone https://github.com/azkaban/azkaban.git ALLPROJECTS/GRADLE/JACOCO/azkaban#azkaban
git clone https://github.com/madisp/stupid.git ALLPROJECTS/GRADLE/JACOCO/madisp#stupid
git clone https://github.com/appium/java-client.git ALLPROJECTS/GRADLE/JACOCO/appium#java-client
git clone https://github.com/spring-projects/spring-integration-samples.git ALLPROJECTS/GRADLE/JACOCO/spring-projects#spring-integration-samples
git clone https://github.com/ehcache/ehcache3.git ALLPROJECTS/GRADLE/JACOCO/ehcache#ehcache3
git clone https://github.com/spotinst/spotinst-sdk-java.git ALLPROJECTS/GRADLE/JACOCO/spotinst#spotinst-sdk-java
git clone https://github.com/googlemaps/google-maps-services-java.git ALLPROJECTS/GRADLE/JACOCO/googlemaps#google-maps-services-java
git clone https://github.com/crate/crate.git ALLPROJECTS/GRADLE/JACOCO/crate#crate
