call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/jdeferred#jdeferred
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/fossasia#susi_server
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/Squarespace#template-compiler
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/skylot#jadx
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/CalebFenton#simplify
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/pedrovgs#AndroidWiFiADB
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/reactor#reactor-core
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/gocd#gocd
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/xbib#cql
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/chennaione#sugar
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/oblac#jodd
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/vavr-io#vavr
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/aNNiMON#Lightweight-Stream-API
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/mambu-gmbh#number2words
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/azkaban#azkaban
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/madisp#stupid
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/appium#java-client
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/spring-projects#spring-integration-samples
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/ehcache#ehcache3
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/spotinst#spotinst-sdk-java
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/googlemaps#google-maps-services-java
call gradle clean build test --continue -p ALLPROJECTS/GRADLE/JACOCO/crate#crate
