git clone https://github.com/appium/java-client.git ALLPROJECTS/GRADLE/JACOCO/appium#java-client
git clone https://github.com/azkaban/azkaban.git ALLPROJECTS/GRADLE/JACOCO/azkaban#azkaban
git clone https://github.com/ben-manes/caffeine.git ALLPROJECTS/GRADLE/JACOCO/ben-manes#caffeine
git clone https://github.com/CalebFenton/simplify.git ALLPROJECTS/GRADLE/JACOCO/CalebFenton#simplify
git clone https://github.com/chennaione/sugar.git ALLPROJECTS/GRADLE/JACOCO/chennaione#sugar
git clone https://github.com/crate/crate.git ALLPROJECTS/GRADLE/JACOCO/crate#crate
git clone https://github.com/gocd/gocd.git ALLPROJECTS/GRADLE/JACOCO/gocd#gocd
git clone https://github.com/igniterealtime/Smack.git ALLPROJECTS/GRADLE/JACOCO/igniterealtime#Smack
git clone https://github.com/madisp/stupid.git ALLPROJECTS/GRADLE/JACOCO/madisp#stupid
git clone https://github.com/mambu-gmbh/number2words.git ALLPROJECTS/GRADLE/JACOCO/mambu-gmbh#number2words
git clone https://github.com/mongodb/mongo-java-driver.git ALLPROJECTS/GRADLE/JACOCO/mongodb#mongo-java-driver
git clone https://github.com/Netflix/conductor.git ALLPROJECTS/GRADLE/JACOCO/Netflix#conductor
git clone https://github.com/oblac/jodd.git ALLPROJECTS/GRADLE/JACOCO/oblac#jodd
git clone https://github.com/resilience4j/resilience4j.git ALLPROJECTS/GRADLE/JACOCO/resilience4j#resilience4j
git clone https://github.com/skylot/jadx.git ALLPROJECTS/GRADLE/JACOCO/skylot#jadx
git clone https://github.com/spotinst/spotinst-sdk-java.git ALLPROJECTS/GRADLE/JACOCO/spotinst#spotinst-sdk-java
git clone https://github.com/springfox/springfox.git ALLPROJECTS/GRADLE/JACOCO/springfox#springfox
git clone https://github.com/Squarespace/template-compiler.git ALLPROJECTS/GRADLE/JACOCO/Squarespace#template-compiler
git clone https://github.com/vavr-io/vavr.git ALLPROJECTS/GRADLE/JACOCO/vavr-io#vavr
git clone https://github.com/web3j/web3j.git ALLPROJECTS/GRADLE/JACOCO/web3j#web3j
