git clone https://github.com/microsoft/lsif-java.git ALLPROJECTS/MAVEN/JACOCO/microsoft#lsif-java
git clone https://github.com/eclipse/eclipse.jdt.ls.git ALLPROJECTS/MAVEN/JACOCO/eclipse#eclipse.jdt.ls
git clone https://github.com/koushikr/jelastic.git ALLPROJECTS/MAVEN/JACOCO/koushikr#jelastic
git clone https://github.com/quarkusio/quarkus.git ALLPROJECTS/MAVEN/JACOCO/quarkusio#quarkus
git clone https://github.com/orientechnologies/orientdb.git ALLPROJECTS/MAVEN/JACOCO/orientechnologies#orientdb
git clone https://github.com/sofastack/sofa-jraft.git ALLPROJECTS/MAVEN/JACOCO/sofastack#sofa-jraft
git clone https://github.com/NanoHttpd/nanohttpd.git ALLPROJECTS/MAVEN/JACOCO/NanoHttpd#nanohttpd
git clone https://github.com/ivan-vasilev/neuralnetworks.git ALLPROJECTS/MAVEN/JACOCO/ivan-vasilev#neuralnetworks
git clone https://github.com/Kong/unirest-java.git ALLPROJECTS/MAVEN/JACOCO/Kong#unirest-java
git clone https://github.com/pmd/pmd.git ALLPROJECTS/MAVEN/JACOCO/pmd#pmd
git clone https://github.com/BroadleafCommerce/BroadleafCommerce.git ALLPROJECTS/MAVEN/JACOCO/BroadleafCommerce#BroadleafCommerce
git clone https://github.com/mabe02/lanterna.git ALLPROJECTS/MAVEN/JACOCO/mabe02#lanterna
git clone https://github.com/joschi/JadConfig.git ALLPROJECTS/MAVEN/JACOCO/joschi#JadConfig
git clone https://github.com/apache/kylin.git ALLPROJECTS/MAVEN/JACOCO/apache#kylin
git clone https://github.com/spring-cloud/spring-cloud-gateway.git ALLPROJECTS/MAVEN/JACOCO/spring-cloud#spring-cloud-gateway
git clone https://github.com/alibaba/druid.git ALLPROJECTS/MAVEN/JACOCO/alibaba#druid
git clone https://github.com/hazelcast/hazelcast.git ALLPROJECTS/MAVEN/JACOCO/hazelcast#hazelcast
git clone https://github.com/dbi1463/SortDescriptor.git ALLPROJECTS/MAVEN/JACOCO/dbi1463#SortDescriptor
git clone https://github.com/zxing/zxing.git ALLPROJECTS/MAVEN/JACOCO/zxing#zxing
git clone https://github.com/btc-ag/service-idl.git ALLPROJECTS/MAVEN/JACOCO/btc-ag#service-idl
git clone https://github.com/eclipse/jetty.project.git ALLPROJECTS/MAVEN/JACOCO/eclipse#jetty.project
git clone https://github.com/ptitjes/jlato.git ALLPROJECTS/MAVEN/JACOCO/ptitjes#jlato
git clone https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition.git ALLPROJECTS/MAVEN/JACOCO/EnterpriseQualityCoding#FizzBuzzEnterpriseEdition
git clone https://github.com/oasis-open/openc2-lycan-java.git ALLPROJECTS/MAVEN/JACOCO/oasis-open#openc2-lycan-java
git clone https://github.com/daniloarcidiacono/commons-lang.git ALLPROJECTS/MAVEN/JACOCO/daniloarcidiacono#commons-lang
git clone https://github.com/spring-cloud/spring-cloud-netflix.git ALLPROJECTS/MAVEN/JACOCO/spring-cloud#spring-cloud-netflix
git clone https://github.com/panda-lang/panda.git ALLPROJECTS/MAVEN/JACOCO/panda-lang#panda
git clone https://github.com/apache/hbase.git ALLPROJECTS/MAVEN/JACOCO/apache#hbase
git clone https://github.com/ctripcorp/apollo.git ALLPROJECTS/MAVEN/JACOCO/ctripcorp#apollo
git clone https://github.com/raphw/byte-buddy.git ALLPROJECTS/MAVEN/JACOCO/raphw#byte-buddy
git clone https://github.com/alibaba/jetcache.git ALLPROJECTS/MAVEN/JACOCO/alibaba#jetcache
git clone https://github.com/alibaba/arthas.git ALLPROJECTS/MAVEN/JACOCO/alibaba#arthas
git clone https://github.com/spotify/apollo.git ALLPROJECTS/MAVEN/JACOCO/spotify#apollo
git clone https://github.com/jeremylong/DependencyCheck.git ALLPROJECTS/MAVEN/JACOCO/jeremylong#DependencyCheck
git clone https://github.com/brunocvcunha/mdmlang.git ALLPROJECTS/MAVEN/JACOCO/brunocvcunha#mdmlang
git clone https://github.com/lettuce-io/lettuce-core.git ALLPROJECTS/MAVEN/JACOCO/lettuce-io#lettuce-core
git clone https://github.com/Anil-Adhikari/IMPL.git ALLPROJECTS/MAVEN/JACOCO/Anil-Adhikari#IMPL
git clone https://github.com/pure4j/pure4j.git ALLPROJECTS/MAVEN/JACOCO/pure4j#pure4j
git clone https://github.com/amaembo/streamex.git ALLPROJECTS/MAVEN/JACOCO/amaembo#streamex
git clone https://github.com/brettwooldridge/HikariCP.git ALLPROJECTS/MAVEN/JACOCO/brettwooldridge#HikariCP
git clone https://github.com/gerryai/pddl-parser.git ALLPROJECTS/MAVEN/JACOCO/gerryai#pddl-parser
git clone https://github.com/sofastack/sofa-rpc.git ALLPROJECTS/MAVEN/JACOCO/sofastack#sofa-rpc
git clone https://github.com/automate-website/waml-io.git ALLPROJECTS/MAVEN/JACOCO/automate-website#waml-io
git clone https://github.com/atomix/atomix.git ALLPROJECTS/MAVEN/JACOCO/atomix#atomix
git clone https://github.com/xuhuisheng/lemon.git ALLPROJECTS/MAVEN/JACOCO/xuhuisheng#lemon
git clone https://github.com/apache/pulsar.git ALLPROJECTS/MAVEN/JACOCO/apache#pulsar
git clone https://github.com/apache/skywalking.git ALLPROJECTS/MAVEN/JACOCO/apache#skywalking
git clone https://github.com/jtablesaw/tablesaw.git ALLPROJECTS/MAVEN/JACOCO/jtablesaw#tablesaw
git clone https://github.com/docker-java/docker-java.git ALLPROJECTS/MAVEN/JACOCO/docker-java#docker-java
git clone https://github.com/FINRAOS/JTAF-XCore.git ALLPROJECTS/MAVEN/JACOCO/FINRAOS#JTAF-XCore
git clone https://github.com/MorphiaOrg/morphia.git ALLPROJECTS/MAVEN/JACOCO/MorphiaOrg#morphia
git clone https://github.com/OryxProject/oryx.git ALLPROJECTS/MAVEN/JACOCO/OryxProject#oryx
git clone https://github.com/apache/dubbo.git ALLPROJECTS/MAVEN/JACOCO/apache#dubbo
git clone https://github.com/jersey/jersey.git ALLPROJECTS/MAVEN/JACOCO/jersey#jersey
git clone https://github.com/square/keywhiz.git ALLPROJECTS/MAVEN/JACOCO/square#keywhiz
git clone https://github.com/modelmapper/modelmapper.git ALLPROJECTS/MAVEN/JACOCO/modelmapper#modelmapper
git clone https://github.com/alibaba/fastjson.git ALLPROJECTS/MAVEN/JACOCO/alibaba#fastjson
git clone https://github.com/opentracing/opentracing-java.git ALLPROJECTS/MAVEN/JACOCO/opentracing#opentracing-java
git clone https://github.com/AxonFramework/AxonFramework.git ALLPROJECTS/MAVEN/JACOCO/AxonFramework#AxonFramework
git clone https://github.com/mybatis/mybatis-3.git ALLPROJECTS/MAVEN/JACOCO/mybatis#mybatis-3
git clone https://github.com/netty/netty.git ALLPROJECTS/MAVEN/JACOCO/netty#netty
git clone https://github.com/JanusGraph/janusgraph.git ALLPROJECTS/MAVEN/JACOCO/JanusGraph#janusgraph
git clone https://github.com/speedment/speedment.git ALLPROJECTS/MAVEN/JACOCO/speedment#speedment
